apiVersion: v1
kind: Secret
metadata:
  name: nubrik-secret
  namespace: nubrik
type: Opaque
stringData:
  # Database password
  DB_PASSWORD: "root"
  POSTGRES_PASSWORD: "root"
  
  # JWT Secret
  JWT_SEED: "dJLK32-nlk23e-LKJ921-lL012s-LH123d0-wlql21-kLJvv8"
  
  # SMTP Password
  SMTP_PASS: "070e88e5e491fa"
  
  # Google OAuth Secret
  GOOGLE_CLIENT_SECRET: "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"