apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: nubrik
spec:
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30173
  type: NodePort